flux_port: 8080
mode: l7
max_retries: 3
tls:
  enabled: false
  cert_file: ./certs/server.crt
  key_file: ./certs/server.key

consul:
  address: localhost:8500

services:
  - name: payments-v1
    matcher: /api/v1/payments
    strategy: round-robin
    health_check:
      path: /health

  - name: payments-v2
    matcher: /api/v2/payments
    strategy: weighted-round-robin
    health_check:
      path: /health

  # - name: users
  #   matcher: /users
  #   strategy: round-robin
  #   health_check:
  #     path: /health